// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfWhjmoc8rQL6FekenxWXyk4hAeOqndo',
    appId: '1:346561229065:web:198888dddc267a08a6e3d8',
    messagingSenderId: '346561229065',
    projectId: 'job-app-77d65',
    authDomain: 'job-app-77d65.firebaseapp.com',
    storageBucket: 'job-app-77d65.firebasestorage.app',
    measurementId: 'G-2NJ4C9ZY3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0gAHxnP-ZLkxXufTyAMRejjtbb-m2mJ8',
    appId: '1:346561229065:android:674e99db622fe4cfa6e3d8',
    messagingSenderId: '346561229065',
    projectId: 'job-app-77d65',
    storageBucket: 'job-app-77d65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4M1ZRpFZPFR4Mm7gtLg_jozpOp2GuvnA',
    appId: '1:346561229065:ios:b91e5b39d9b39346a6e3d8',
    messagingSenderId: '346561229065',
    projectId: 'job-app-77d65',
    storageBucket: 'job-app-77d65.firebasestorage.app',
    iosBundleId: 'com.example.jobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4M1ZRpFZPFR4Mm7gtLg_jozpOp2GuvnA',
    appId: '1:346561229065:ios:b91e5b39d9b39346a6e3d8',
    messagingSenderId: '346561229065',
    projectId: 'job-app-77d65',
    storageBucket: 'job-app-77d65.firebasestorage.app',
    iosBundleId: 'com.example.jobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIfWhjmoc8rQL6FekenxWXyk4hAeOqndo',
    appId: '1:346561229065:web:6c556c660f5e7f28a6e3d8',
    messagingSenderId: '346561229065',
    projectId: 'job-app-77d65',
    authDomain: 'job-app-77d65.firebaseapp.com',
    storageBucket: 'job-app-77d65.firebasestorage.app',
    measurementId: 'G-507GFJ1L5L',
  );
}
